services:
  # Geth サービス
  geth:
    image: ethereum/client-go:stable
    container_name: local_geth
    ports:
      - "8545:8545"       # HTTP-RPC
      - "8546:8546"       # WS-RPC
      - "30303:30303"     # P2P (TCP)
      - "30303:30303/udp" # P2P (UDP)
    volumes:
      - geth_data:/root/.ethereum
      - ./geth/genesis.json:/root/genesis.json
      - ./geth/entrypoint.sh:/usr/local/bin/entrypoint.sh

    entrypoint: /usr/local/bin/entrypoint.sh
    command:
      - --verbosity
      - "2" 
      - --datadir
      - /root/.ethereum
      - --dev
      - --dev.period
      - "1"
      # --- HTTP RPC ---
      - --http
      - --http.addr
      - "0.0.0.0"
      - --http.port
      - "8545"
      - --http.corsdomain
      - "*"
      - --http.vhosts
      - "*"
      - --http.api
      - "eth,net,web3"
      # --- WebSocket RPC ---
      - --ws
      - --ws.addr
      - "0.0.0.0"
      - --ws.port
      - "8546"
      - --ws.origins
      - "*"
      - --ws.api
      - "eth,net,web3"
      # --- その他 ---
      - --authrpc.port
      - "0" # 認証RPC(8551ポート)を無効化

  # Foundry Anvil サービス
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: local_anvil
    ports:
      # ✅ Gethとポートが競合しないようにホスト側ポートを 8544 に変更
      - "8544:8545"
    entrypoint: /bin/sh
    command:
      - -c
      - "anvil --host 0.0.0.0 --block-base-fee-per-gas 0"

  # ArLocal サービス
  arlocal:
    image: node:22
    container_name: arlocal-instance
    ports:
      - "1984:1984"
    working_dir: /app
    volumes:
      - arlocal_data:/app/data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1984"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    entrypoint: /bin/sh
    command:
      - -c
      - "npm install -g arlocal && arlocal --persist --data-path /app/data"

  # Hardhat 開発環境サービス
  hardhat:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    container_name: local_hardhat
    working_dir: /app
    volumes:
      - ./hardhat:/app
      - /app/node_modules
    depends_on:
      - geth # 依存先をgethに変更
    tty: true
    stdin_open: true

volumes:
  geth_data: {} # Gethのデータ保存用ボリューム
  arlocal_data: {} # ArLocalのデータ保存用ボリューム