services:
  # Foundry Anvil サービス
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --host 0.0.0.0
    ports:
      - "8545:8545"
    container_name: local_anvil

  arlocal:
      image: node:22-slim # Node.jsのイメージを使用（ArLocalの動作に必要なため）
      container_name: arlocal-instance
      ports:
        - "1984:1984" # ArLocalのデフォルトポートをホストに公開
      working_dir: /app
      volumes:
        - arlocal_data:/app/data # 永続化のためのボリューム
      command: sh -c "npm install -g arlocal && arlocal --persist-data --data-path /app/data"
      restart: always # コンテナが終了した場合に自動で再起動
      healthcheck: # ヘルスチェックの定義
        test: ["CMD", "curl", "-f", "http://localhost:1984"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s

  # Hardhat 開発環境サービス
  hardhat:
    # Node.jsの公式イメージを使用
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    container_name: local_hardhat
    working_dir: /app # working_dirを/appに修正
    volumes:
      - ./hardhat:/app
      - /app/node_modules
    depends_on:
      - anvil
    tty: true
    stdin_open: true

volumes:
  arlocal_data: # ArLocalのデータ保存用ボリューム
